WebApp/Controllers/HomeController.cs
using MPMG.Services;
using MPMG.Util;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly PlanilhaAnpService planilhaAnpService;
        private readonly ObterMunicipioAnpService listarMunicipiosService;

        public HomeController()
        {
            planilhaAnpService = new PlanilhaAnpService();
            listarMunicipiosService = new ObterMunicipioAnpService();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public JsonResult ObterMunicipioAnpPorNomeAno(List<int> anosReferentes, string nomeMunicipio)
        {
            try
            {
                var municipio = listarMunicipiosService.ObterMunicipioAnpPorNomeAno(anosReferentes, nomeMunicipio);
                List<string> listaMunicipios = new List<string>();

                if (municipio == null)
                    listaMunicipios = listarMunicipiosService.ListarMunicipiosAnpPorAno(anosReferentes);

                return Json(new
                {
                    municipioSelecionado = nomeMunicipio,
                    anosSelecionados = anosReferentes,
                    municipioReferente = municipio,
                    listaMunicipios
                });

            }
            catch (Exception ex)
            {
                return Json(new { 
                    error = ex.Message,
                    stackTrace = ex.StackTrace,
                    anosReferentes,
                    nomeMunicipio
                });
            }
        }

        public ActionResult AtualizarTabelaAnp()
        {
            try
            {
                planilhaAnpService.ObterPlanilhaAnpCombustiveisEGravar();
                planilhaAnpService.PopularBancoComDadosAnp(Constantes.NOME_ARQUIVO_ANP_PRECOS);
            }
            catch (Exception ex)
            {

                return Json(new { sucesso = false, mensagem = "Ocorreu um erro ao atualizar a planilha da ANP", erro = ex.Message });
            }

            return Json(new { sucesso = true, mensagem = "Planilha ANP atualizada com sucesso" });
        }

    }
}

WebApp/Controllers/TabelaUsuarioController.cs
using MPMG.Interfaces.DTO;
using MPMG.Services;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class TabelaUsuarioController : Controller
    {
        private readonly TabelaUsuarioService tabelaUsuarioService;
        private readonly CupomFiscalService cupomFiscalService;
        private readonly ExportacaoExcelService exportacaoExcelService;

        public TabelaUsuarioController()
        {
            tabelaUsuarioService = new TabelaUsuarioService();
            cupomFiscalService = new CupomFiscalService();
            exportacaoExcelService = new ExportacaoExcelService();
        }

        public JsonResult CadastrarTabela(TabelaUsuario TabelaUsuario)
        {
            try
            {
                tabelaUsuarioService.CadastrarTabela(
                TabelaUsuario.SGDP,
                TabelaUsuario.AnosReferentes,
                TabelaUsuario.NomeMunicipioReferente,
                TabelaUsuario.NomeMunicipio,
                TabelaUsuario.DataGeracao,
                TabelaUsuario.Titulo1,
                TabelaUsuario.Titulo2,
                TabelaUsuario.Titulo3,
                TabelaUsuario.AnalistaResponsavel);

                return Json(new
                {
                    Mensagem = "Sucesso ao cadastrar tabela",
                    DataGeracao = DateTime.Now
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Mensagem = "Ocorreu um erro ao cadastrar tabela",
                    MensagemExcecao = ex.Message,
                    StackTraceExcecao = ex.StackTrace
                });
            }
        }

        public ActionResult ExportarTabelasParaExcel(DadosTabelaDto DadosTabela,
                                                     List<AnpxNotaFiscalModelDto> ListaTabelaAnpxNota,
                                                     List<CupomFiscalDto> ListaCuponsFiscais,
                                                     List<OutrasInformacoesModelDto> ListaOutrasInformacoes)
        {
            try
            {
                var documento = exportacaoExcelService.ExportarDadosParaExcel(DadosTabela, ListaTabelaAnpxNota, ListaCuponsFiscais, ListaOutrasInformacoes);

                if(documento == null || documento.Length == 0)
                    return Json(new
                    {
                        Sucesso = false,
                        Mensagem = "Ocorreu um erro ao exportar o documento"
                    });

                string identificadorArquivo = Guid.NewGuid().ToString();
                TempData[identificadorArquivo] = documento;
                TempData.Keep(identificadorArquivo);

                return RetornarIdentificadorArquivoParaDownload(identificadorArquivo);
            }
            catch(Exception ex)
            {
                return Json(new
                {
                    Sucesso = false,
                    Mensagem = "Ocorreu um erro inesperado"
                });
            }
            
        }

        public ActionResult FazerDownloadDeExcel(string identificadorArquivo)
        {
            try
            {
                if (TempData[identificadorArquivo] != null)
                {
                    byte[] arquivoGerado = (byte[])TempData[identificadorArquivo];
                    return File(arquivoGerado, "application/vnd.ms-excel", identificadorArquivo + ".xlsx");
                }
                else
                {
                    return new EmptyResult();
                }
            }
            catch (Exception ex)
            {

                return Json(new
                {
                    Sucesso = false,
                    Mensagem = "Ocorreu um erro ao efetuar download"
                });
            }
        }

        public ActionResult Index(string valorSgdp = null)
        {
            TabelaUsuarioDto tabelaAnpXNota = new TabelaUsuarioDto();
            TabelaUsuarioDto tabelaOutrasInfos = new TabelaUsuarioDto();
            List<CupomFiscalDto> tabelaCuponsFiscais = new List<CupomFiscalDto>();

            try
            {
                tabelaAnpXNota = tabelaUsuarioService.ObterTabelaComDadosAnpxNotaFiscal(valorSgdp);
                tabelaCuponsFiscais = cupomFiscalService.ListarCuponsFiscaisPorSgdp(valorSgdp);
                tabelaOutrasInfos = tabelaUsuarioService.ObterTabelaOutrasInformacoes(valorSgdp);
            }
            catch (Exception ex) { }
                return View("ListarTabelas", new ListarTabelasModel
            {
                ValorSgdp = valorSgdp,
                TabelaAnpXNota = tabelaAnpXNota,
                TabelaOutrasInformacoes = tabelaOutrasInfos,
                TabelaCuponsFicais = tabelaCuponsFiscais
            });
        }

        private JsonResult RetornarIdentificadorArquivoParaDownload(string identificadorArquivo)
        {
            return Json(new
            {
                Sucesso = true,
                Mensagem = string.Empty,
                IdentificadorArquivo = identificadorArquivo
            });
        }
    }
}

WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Cadastrar Tabela";
}
<div class="form-example-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="form-example-wrap mg-t-30">
                    <div class="cmp-tb-hd cmp-int-hd">
                        <h3>Cadastrar Nova Tabela</h3>
                        <p>Digite os campos abaixo para criar uma nova tabela</p>
                        <img class="carregando" src="~/img/loading.gif" />
                    </div>
                    <div class="form-example-int form-horizental">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-4 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm required">SGDP</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" id="sgdp" maxlength="20">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-example-int form-horizental mg-t-15">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-4 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm">Analista Responsável</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <div class="nk-int-st">
                                        <input id="analista-resp" type="text" class="form-control input-sm">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-example-int form-horizental mg-t-15">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-4 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm">Data Geração da Tabela</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <div>
                                        <input type="text" id="data-geracao" class="form-control input-sm" name="data-geracao" readonly>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-example-int form-horizental mg-t-15">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-4 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm required">Município(s)</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <div class="nk-int-st">
                                        <select class="form-control municipios-anp-busca" id="municipios"></select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-example-int form-horizental mg-t-15">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-4 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm required">Ano(s) referentes</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <div class="bootstrap-select">
                                        <select class="municipios-anp-busca form-control" id="anos-referentes" multiple="multiple">
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="button-icon-btn">
                        <button class="btn btn-default btn-icon-notika required" id="check-disponibilidade-anp">
                            Checar disponibilidade tabela ANP *
                        </button>
                    </div>
                    <div class="form-example-int form-horizental mg-t-15" id="municipios-anp-div">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-4 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm required">Municipio(s) Referência</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <div class="nk-int-st">
                                        <select class="form-control" id="municipios-anp"></select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-example-int form-horizental mg-t-15">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-4 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm required">Título Aba 1 - NFs x ANP</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <div class="nk-int-st">
                                        <input type="text" id="titulo1" class="form-control input-sm">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-example-int form-horizental mg-t-15">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-4 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm required">Título Aba 2 - Cupons Fiscais</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <div class="nk-int-st">
                                        <input type="text" id="titulo2" class="form-control input-sm">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-example-int form-horizental mg-t-15">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-4 col-md-3 col-sm-3 col-xs-12">
                                    <label class="hrzn-fm required">Título Aba 3 - Outras Informações</label>
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <div class="nk-int-st">
                                        <input type="text" id="titulo3" class="form-control input-sm">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="button-icon-btn">
                        <button class="btn btn-default btn-icon-notika" id="cadastrar-tabela">
                            Enviar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section JavascriptPagina {
    <script type="text/javascript">
        $(document).ready(function () {
            $(".carregando").hide();
        });

        var urlObterMunicipioPorNomeAno = '@Url.Action("ObterMunicipioAnpPorNomeAno", "Home")',
            urlCadastrarTabelaUsuario = '@Url.Action("CadastrarTabela", "TabelaUsuario")';

    </script>
    <script type="text/javascript" src="~/Scripts/ObterExcel/obterExcel.js"></script>
    <script type="text/javascript" src="~/Scripts/Municipios/municipio.js"></script>
    <script type="text/javascript" src="~/Scripts/TabelaUsuario/cadastrarTabela.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-select.js"></script>
}